//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_hostal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.Reserva_Usuario = new HashSet<Reserva_Usuario>();
        }
    
        public int id { get; set; }
        public string detalle { get; set; }
        public int idPasajero { get; set; }
        public System.DateTime checkIn { get; set; }
        public System.DateTime checkOut { get; set; }
        public decimal montoPagado { get; set; }
        public decimal montoTotal { get; set; }
        public int idEstadoR { get; set; }
        public int idUserUpdate { get; set; }
        public int idHab { get; set; }
    
        public virtual EstadoReserva EstadoReserva { get; set; }
        public virtual Habitacion Habitacion { get; set; }
        public virtual Pasajero Pasajero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva_Usuario> Reserva_Usuario { get; set; }
    }
}
