//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_hostal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int id { get; set; }
        public int idReserva { get; set; }
        public int idMetodoPago { get; set; }
        public int idUserCreate { get; set; }
        public int idUserUpdate { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal monto { get; set; }
    
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
